cmb/views/aluno.py
"""
Copyright (c) CMB/EB 2023, All Rights Reserved 

THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED 
IN THIS NOTICE BE LIABLE FOR ANY CLAIM OR CONSEQUENTIAL DAMAGES OR ANY 
DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Author Taylor Lopes <taylor.lopes@eb.mil.br>
""" 

# Gerenciamento de rotas e rotinas de Alunos

from flask import Blueprint, render_template, flash, request, session, url_for, redirect
from cmb.plugins.database import db
from cmb.libs.models import Aluno, Turma, Perfil
from cmb.libs.forms import TurmaForm, AlunoForm
from werkzeug.datastructures import ImmutableMultiDict
from cmb.libs.util import obj2dict, get_hashed_password 
from datetime import datetime
from config import TIMEZONE
from urllib.parse import quote_plus


# Define Blueprint
aluno = Blueprint('aluno', __name__) 

@aluno.post('/alunos')
def add_aluno():
    """
    Adiciona uma aluno
    """

    # Somente admin pode realizar esta operação
    if not Perfil.is_admin():
        return render_template('403.html', ip=request.environ.get('REMOTE_ADDR'))    

    # Obtém dados do formulário
    nome = request.form['nome'].strip().upper() 
    matricula = request.form['matricula'].strip()
    id_turma = request.form['id_turma']    
    ativo = '1' if 'aluno_ativo' in request.form else '0'

    # Valida se já existe a turma
    if db.session.query(Aluno).filter_by(matricula=matricula).count() > 0:
        flash(f"Aluno com matrícula {matricula} já existe.", category='error') 
        return redirect(url_for("painel.inicial", _anchor='manutencao-alunos'))    

    # Valida os campos do formulário
    form = AlunoForm()
    form.id_turma.choices  = [(turma.id, turma.nome) for turma in Turma.query.all()]
    if not form.validate_on_submit():
        for message in list(form.errors.values()):
            flash(message[0], category='error')
        return redirect(url_for("painel.inicial", _anchor='manutencao-alunos')) 

    # Tenta adicionar os dados
    try:
        aluno = Aluno(nome=nome, matricula=matricula, id_turma=id_turma, ativo=ativo)
        db.session.add(aluno) 
        db.session.commit() 
        flash('Aluno adicionado com sucesso.', category='success') 
    except Exception as e:
        db.session.rollback()
        db.session.flush() 
        flash('Falha ao adicionar o aluno.', category='error') 
    return redirect(url_for("painel.inicial", _anchor='manutencao-alunos')) 


@aluno.post('/alunos/<matricula>/del')
def del_aluno(matricula):
    """
    Exclui uma aluno
    """ 

    # Somente admin pode realizar esta operação
    if not Perfil.is_admin():
        return render_template('403.html', ip=request.environ.get('REMOTE_ADDR'))   
        
    try:
        aluno = Aluno.query.filter_by(matricula=matricula).one()
        db.session.delete(aluno)
        db.session.commit()
        flash('Aluno excluído com sucesso.', category='success') 
    except Exception as e:
        db.session.rollback()
        db.session.flush() 
        flash('Falha ao excluir: o aluno possui vínculos.', category='error') 
    return redirect(url_for("painel.inicial", _anchor='manutencao-alunos')) 


@aluno.post('/alunos/<matricula>/edit')
def update_aluno_edit(matricula):
    """
    Atualiza aluno
    """    

    # Somente admin pode realizar esta operação
    if not Perfil.is_admin():
        return render_template('403.html', ip=request.environ.get('REMOTE_ADDR'))        

    # Obtém dados do formulário
    id = request.form['id'] 
    nome = request.form['nome'].strip().upper() 
    matricula = request.form['matricula'].strip() 
    id_turma = request.form['id_turma'] 
    ativo = '1' if 'aluno_ativo' in request.form else '0'


    aluno = Aluno.query.filter_by(id=id).one()

    # Valida se já existe a turma
    if matricula != aluno.matricula:
        if db.session.query(Aluno).filter_by(matricula=matricula).count() > 0:
            flash(f"Aluno com matrícula {matricula} já existe.", category='error') 
            return redirect(url_for("painel.inicial", _anchor='manutencao-alunos'))    

    # Valida os campos do formulário
    form = AlunoForm()
    form.id_turma.choices  = [(turma.id, turma.nome) for turma in Turma.query.all()]
    if not form.validate_on_submit():
        for message in list(form.errors.values()):
            flash(message[0], category='error')
        return redirect(url_for("painel.inicial", _anchor='manutencao-alunos')) 

    # Tenta atualizar os dados
    try:
        aluno.matricula = matricula
        aluno.nome = nome
        aluno.ativo = ativo
        aluno.id_turma = id_turma 
        db.session.commit() 
        flash('Aluno atualizado com sucesso.', category='success') 
    except Exception as e:
        db.session.rollback()
        db.session.flush() 
        flash('Falha ao atualizar o aluno.', category='error') 
    return redirect(url_for("painel.inicial", _anchor='manutencao-alunos')) 



@aluno.get('/alunos/matricula')
def get_aluno_matricula():
    """
    Obtém alunos com parte de matrícula (autocomplete)
    """     
    busca = f"%{request.args['matricula']}%"    
    alunos = db.session.execute(db.select(Aluno).filter(Aluno.ativo == '1', Aluno.matricula.like(busca)).order_by(Aluno.nome)).scalars().fetchall()
    suggestions = []
    for u in alunos:
        aluno = u.__dict__     
        turma = u.turma.__dict__   
        suggestions.append({
            "value": aluno['matricula'], 
            "matricula": aluno['matricula'], 
            "nome": aluno['nome'], 
            "id_turma": aluno['id_turma'],
            "turma": turma['nome']
        })
    return {"suggestions": suggestions}


@aluno.get('/alunos/nome')
def get_aluno_nome():
    """
    Obtém alunos com parte do nome (autocomplete)
    """     
    busca = f"%{request.args['aluno']}%".upper()

    alunos = db.session.execute(db.select(Aluno).filter(Aluno.ativo == '1', Aluno.nome.like(busca)).order_by(Aluno.nome)).scalars().fetchall()
    suggestions = []
    for u in alunos:
        aluno = u.__dict__     
        turma = u.turma.__dict__   
        suggestions.append({
            "value": aluno['nome'], 
            "matricula": aluno['matricula'], 
            "nome": aluno['nome'], 
            "id_turma": aluno['id_turma'],
            "turma": turma['nome']
        })
    return {"suggestions": suggestions}

cmb/views/auth.py
"""
Copyright (c) CMB/EB 2023, All Rights Reserved 

THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED 
IN THIS NOTICE BE LIABLE FOR ANY CLAIM OR CONSEQUENTIAL DAMAGES OR ANY 
DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Author Taylor Lopes <taylor.lopes@eb.mil.br>
""" 

# Gerenciamento de rotas e rotinas de Autenticação (Auth)

from flask import Blueprint, current_app, render_template, flash, request, session, url_for, redirect
from cmb.plugins.database import db 
from cmb.libs.models import Perfil, Registro
from cmb.libs.forms import PerfilForm
from cmb.libs.util import populate 
from datetime import datetime 
from config import TIMEZONE
from cmb.libs.util import check_password
 

# Define Blueprint
auth = Blueprint('auth', __name__)


@auth.get('/')
@auth.get('/login')
def login():    
    """
    Exibe tela de login
    """   
    
    if 'login' not in session:
        session['perfil'] = {"nome": session['perfil']['nome']} if "perfil" in session else {"nome": ""}     
        perfis = Perfil.query.all()        
        return render_template('login.html', perfis=perfis)
    else:
        return redirect(url_for("painel.inicial"))

 
@auth.get('/logout')
def logout():     
    """
    Efetua o logout
    """       
    session.clear()
    return redirect(url_for("auth.login"))   


@auth.post('/autenticar')
def autenticar(): 
    """
    Autenticação do usuário
    """
    id = request.form['id']
    senha = request.form['senha'] 

    # Valida os campos do formulário
    form = PerfilForm()
    form.id.choices  = [(perfil.id, perfil.nome) for perfil in Perfil.query.all()]
    if not form.validate_on_submit():
        for message in list(form.errors.values()):
            flash(message[0], category='error')
        return redirect(url_for("auth.login")) 
 
    # Busca o perfil e compara a senha
    perfil = Perfil.query.filter_by(id=id).first()

    # Se usuário autenticado com falha
    if not check_password(senha, perfil.senha):
        flash('Perfil e senha não conferem.', category='error')
        return redirect(url_for("auth.login"))    

    # Inicializa dados do registro persistidos na sessão
    Registro.reset()

    # Se usuário autenticado com sucesso
    session['login']  = True
    perfil.senha = None
    session['perfil'] = perfil.as_dict()
    return redirect(url_for("painel.inicial"))

cmb/views/painel.py
"""
Copyright (c) CMB/EB 2023, All Rights Reserved 

THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED 
IN THIS NOTICE BE LIABLE FOR ANY CLAIM OR CONSEQUENTIAL DAMAGES OR ANY 
DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Author Taylor Lopes <taylor.lopes@eb.mil.br>
""" 

# Gerenciamento de rotas e rotinas do painel principal

from flask import Blueprint, render_template, flash, request, session, url_for, redirect
from cmb.libs.models import Perfil, Turma, Aluno, Registro
from datetime import datetime, timedelta
from config import TIMEZONE

from socket import gethostname, gethostbyname

# Define Blueprint
painel = Blueprint('painel', __name__)

@painel.get('/painel')
def inicial():
    """
    Exibe o painel principal
    """  
    
    # Verifica se o usuário está logado
    if 'login' not in session:
        return render_template('403.html', ip=request.environ.get('REMOTE_ADDR'))
    
    # Obtém os dados do painel 
    perfis = Perfil.query.all() 
    turmas = Turma.query.order_by(Turma.ativo.desc(), Turma.nome.asc()).all()
    turmas_ativas = Turma.query.filter_by(ativo="1").order_by(Turma.nome.asc()).all()
    alunos = Aluno.query.order_by(Aluno.ativo.desc(), Aluno.nome.asc()).all()    
    dt1 = request.args['dt1']+':00' if 'dt1' in request.args else datetime.now(TIMEZONE).replace(hour=0, minute=0, second=0).strftime('%Y-%m-%d %H:%M:%S')
    dt2 = request.args['dt2']+':59' if 'dt2' in request.args else datetime.now(TIMEZONE).replace(hour=23, minute=59, second=59).strftime('%Y-%m-%d %H:%M:%S')
    hoje = datetime.now(TIMEZONE).replace(hour=0, minute=0, second=0, microsecond=0)
    
    # Persiste na sessão as datas (período) da lista de entrada/saída
    if 'dt1' in request.args:
        session['dt1'] = dt1
    dt1 = session['dt1'] if 'dt1' in session else dt1       
    if 'dt2' in request.args:
        session['dt2'] = dt2
    dt2 = session['dt2'] if 'dt2' in session else dt2     

    # Limpa os campos do registro, se solicitado
    if 'reset' in request.args:
        Registro.reset()

    # Obtém os registros de alunos conforme datas do formulário
    registros = Registro.query.filter(Registro.dt_evento.between(dt1, dt2)).order_by(Registro.dt_evento.desc(), Registro.id.desc()).all()

    # Renderiza a template 
    return render_template(
        'painel.html', 
        perfis=perfis, 
        turmas=turmas, 
        turmas_ativas=turmas_ativas,        
        alunos=alunos, 
        registros=registros, 
        hoje=hoje, 
        dt1=dt1, 
        dt2=dt2
    )

cmb/views/turma.py
"""
Copyright (c) CMB/EB 2023, All Rights Reserved 

THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED 
IN THIS NOTICE BE LIABLE FOR ANY CLAIM OR CONSEQUENTIAL DAMAGES OR ANY 
DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Author Taylor Lopes <taylor.lopes@eb.mil.br>
""" 

# Gerenciamento de rotas e rotinas de Ano/Turmas

from flask import Blueprint, render_template, flash, request, session, url_for, redirect
from cmb.plugins.database import db
from cmb.libs.models import Turma, Perfil
from cmb.libs.forms import TurmaForm
from werkzeug.datastructures import ImmutableMultiDict
from cmb.libs.util import get_hashed_password 
from datetime import datetime
from config import TIMEZONE

# Define Blueprint
turma = Blueprint('turma', __name__)


@turma.post('/turmas')
def add_turma():
    """
    Adiciona uma turma
    """    

    # Somente admin pode realizar esta operação
    if not Perfil.is_admin():
        return render_template('403.html', ip=request.environ.get('REMOTE_ADDR'))       

    # Torna compatível nome de campos que vem do formulário com validador libs.forms.py
    dataform = request.form.to_dict()  
    dataform['nome'] = request.form['turma']
    request.form = ImmutableMultiDict(dataform)

    # Obtém dados do formulário
    nome = request.form['nome'] 
    ativo = '1' if 'turma_ativo' in request.form else '0'

    # Valida se já existe a turma
    if db.session.query(Turma).filter_by(nome=nome).count() > 0:
        flash(f"Falha ao adicionar. Turma {nome} já existe.", category='error') 
        return redirect(url_for("painel.inicial", _anchor='manutencao-turmas'))    

    # Valida os campos do formulário
    form = TurmaForm()
    if not form.validate_on_submit():
        for message in list(form.errors.values()):
            flash(message[0], category='error')
        return redirect(url_for("painel.inicial", _anchor='manutencao-turmas')) 
 
    # Tenta adicionar os dados
    try:
        turma = Turma(nome=nome, ativo=ativo)
        db.session.add(turma) 
        db.session.commit() 
        flash('Turma adicionada com sucesso.', category='success') 
    except Exception as e:
        db.session.rollback()
        db.session.flush() 
        flash('Falha ao adicionar a turma.', category='error') 
    return redirect(url_for("painel.inicial", _anchor='manutencao-turmas')) 


@turma.post('/turmas/<id>/del')
def del_turma(id):
    """
    Exclui uma turma
    """    
    
    # Somente admin pode realizar esta operação
    if not Perfil.is_admin():
        return render_template('403.html', ip=request.environ.get('REMOTE_ADDR'))   
    
    try:
        turma = Turma.query.filter_by(id=id).one()
        db.session.delete(turma)
        db.session.commit()
        flash('Turma excluída com sucesso.', category='success') 
    except Exception as e:
        db.session.rollback()
        db.session.flush() 
        flash('Falha ao excluir: a turma possui vínculos.', category='error') 
    return redirect(url_for("painel.inicial", _anchor='manutencao-turmas')) 



@turma.post('/turmas/<id>/edit')
def update_turma_edit(id):
    """
    Atualiza turma
    """     

    # Somente admin pode realizar esta operação
    if not Perfil.is_admin():
        return render_template('403.html', ip=request.environ.get('REMOTE_ADDR'))       
 
    # Torna compatível nome de campos que vem do formulário com validador libs.forms.py
    dataform = request.form.to_dict()  
    dataform['nome'] = request.form['turma']
    request.form = ImmutableMultiDict(dataform)     

    # Obtém dados do formulário
    id = request.form['id'] 
    nome = request.form['nome'].strip() 
    ativo = '1' if 'turma_ativo' in request.form else '0'
    
    turma = Turma.query.filter_by(id=id).one() 

    # Valida os campos do formulário
    form = TurmaForm() 
    if not form.validate_on_submit():
        for message in list(form.errors.values()):
            flash(message[0], category='error')
        return redirect(url_for("painel.inicial", _anchor='manutencao-turmas')) 

    # Tenta atualizar os dados
    try:        
        turma.nome = nome
        turma.ativo = ativo
        db.session.commit() 
        flash('Turma atualizada com sucesso.', category='success') 
    except Exception as e:
        db.session.rollback()
        db.session.flush() 
        flash('Falha ao atualizar a turma.', category='error') 
    return redirect(url_for("painel.inicial", _anchor='manutencao-turmas')) 

cmb/templates/manutencao.html
<div class="d-flex align-items-start">
    <div class="nav flex-column nav-pills me-3 bg-white" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <button class="nav-link active" id="v-pills-aluno-tab" data-bs-toggle="pill" data-bs-target="#v-pills-aluno"
            type="button" role="tab" aria-controls="v-pills-aluno" aria-selected="true">Alunos</button>
        <button class="nav-link" id="v-pills-turma-tab" data-bs-toggle="pill" data-bs-target="#v-pills-turma"
            type="button" role="tab" aria-controls="v-pills-turma" aria-selected="false">Turmas</button>
        <button class="nav-link" id="v-pills-senha-tab" data-bs-toggle="pill" data-bs-target="#v-pills-senha"
            type="button" role="tab" aria-controls="v-pills-senha" aria-selected="false">Senhas</button>
    </div>
    <div class="tab-content container" id="v-pills-tabContent">
        <!-- Alunos -->
        <div class="tab-pane fade show active" id="v-pills-aluno" role="tabpanel" aria-labelledby="v-pills-aluno-tab">
            <p class="text-muted mb-3">Cadastro de alunos</p>    
            <form id="frm-aluno" class="row g-3" method="post" action="{{ url_for('aluno.add_aluno') }}" accept-charset="utf-8">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />                
                <input type="hidden" name="id" id="id_aluno" value="" />                
                <div class="col-sm-2">
                    <input type="text" name="matricula" id="matricula" class="form-control" placeholder="Matrícula">
                </div>                
                <div class="col-sm-5">
                    <input type="text" name="nome" id="nome" class="form-control uppercase" placeholder="Nome do aluno">
                </div>
                <div class="col-sm-2 ">
                    <select class="form-select" name="id_turma" id="id_turma" aria-label="Default select example">
                        <option value="">Ano/Turma</option>
                        {% for turma in turmas %}                        
                        <option value="{{ turma.id }}">{{ turma.nome }}</option>
                        {% endfor %}
                    </select>
                </div>     
                <div class="col-auto">
                    <div class="form-check mt-2">
                        <input class="form-check-input" type="checkbox" value="1" id="aluno-ativo" name="aluno_ativo" checked>
                        <label class="form-check-label" for="aluno-ativo">
                          Ativo
                        </label>
                    </div>
                </div>                           
                <div class="col-sm-2 d-inline-block">
                    <button type="submit" class="btn btn-primary btn-aluno-add">Adicionar</button>
                    <button type="submit" class="btn btn-primary btn-aluno-update d-none">Alterar</button>
                    <button type="button" class="btn btn-danger btn-aluno-update-cancelar d-none" data-url="{{ url_for('aluno.add_aluno') }}">Cancelar</button>
                </div>
            </form>
            <hr class="hr my-4" />
            <!-- Datatables Alunos-->
            <div class="col-sm-12 my-3">
                <table id="tbl-alunos" class="table nowrap table-striped" style="width:100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>                            
                            <th>Matrícula</th>
                            <th>Nome</th>
                            <th>Ano/Turma</th>
                            <th>Ativo</th>
                            <th>~</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for aluno in alunos %}
                        <tr>
                            <td class="align-middle">{{ aluno.id }}</td>                            
                            <td class="align-middle">{{ aluno.matricula }}</td>
                            <td class="align-middle">{{ aluno.nome }}</td>
                            <td class="align-middle">{{ aluno.turma.nome }}</td>
                            <td class="align-middle">{{ 'Sim' if aluno.ativo == '1' else 'Não' }}</td>
                            <td class="align-middle text-end">        
                                <button type="button" class="btn btn-light btn-aluno-edit" data-id="{{ aluno.id }}"  data-matricula="{{ aluno.matricula }}" data-nome="{{ aluno.nome }}" data-id-turma="{{ aluno.id_turma }}" data-aluno-ativo="{{ aluno.ativo }}"  data-url="{{ url_for('aluno.update_aluno_edit', matricula=aluno.matricula) }}">
                                    <i class="fa-regular fa-pen text-primary"></i>
                                </button>                                   
                                <button type="button" class="btn btn-light btn-aluno-del" data-matricula="{{ aluno.matricula }}" data-nome="{{ aluno.nome }}" data-url="{{ url_for('aluno.del_aluno', matricula=aluno.matricula) }}">
                                    <i class="fa-regular fa-trash-can text-primary"></i>
                                </button>                                
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div> <!-- /Datatables Alunos-->
        </div> <!-- /Alunos -->

        <!-- Turmas -->
        <div class="tab-pane fade" id="v-pills-turma" role="tabpanel" aria-labelledby="v-pills-turma-tab">
            <p class="text-muted mb-3">Cadastro de turmas</p>   
            <form id="frm-turma" class="row g-3" method="post" action="{{ url_for('turma.add_turma') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <input type="hidden" name="id" id="id_turma_edit" value="" />    
                <div class="col">
                    <input type="text" name="turma" id="turma" class="form-control" placeholder="Ano/Turma">
                </div>
                <div class="col-auto">
                    <div class="form-check mt-2">
                        <input class="form-check-input" type="checkbox" value="1" id="turma-ativo" name="turma_ativo" checked>
                        <label class="form-check-label" for="turma-ativo">
                          Ativo
                        </label>
                    </div>
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary btn-turma-add">Adicionar</button>
                    <button type="submit" class="btn btn-primary btn-turma-update d-none">Alterar</button>
                    <button type="button" class="btn btn-danger btn-turma-update-cancelar d-none" data-url="{{ url_for('turma.add_turma') }}">Cancelar</button>                    
                </div>
            </form>
            <hr class="hr my-4" />
            <!-- Datatables Turmas-->
            <div class="col-sm-12 my-3">
                <table id="tbl-turmas" class="table nowrap table-striped" style="width:100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ano/Turma</th>
                            <th>Ativo</th>
                            <th>~</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for turma in turmas %}
                        <tr>
                            <td class="align-middle">{{ turma.id }}</td>
                            <td class="align-middle">{{ turma.nome }}</td>
                            <td class="align-middle">{{ 'Sim' if turma.ativo == '1' else 'Não' }}</td>
                            <td class="align-middle text-end">                                    
                                <button type="button" class="btn btn-light btn-turma-edit" data-id="{{ turma.id }}"  data-turma="{{ turma.nome }}" data-turma-ativo="{{ turma.ativo }}" data-url="{{ url_for('turma.update_turma_edit', id=turma.id) }}">
                                    <i class="fa-regular fa-pen text-primary"></i>
                                </button> 
                                <button type="button" class="btn btn-light btn-turma-del" data-id="{{ turma.id }}" data-turma="{{ turma.nome }}" data-url="{{ url_for('turma.del_turma', id=turma.id) }}">
                                    <i class="fa-regular fa-trash-can text-primary"></i>
                                </button>                                
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div> <!-- /Datatables Turmas-->
        </div><!-- /Turmas -->


        <!-- Senhas -->
        <div class="tab-pane fade" id="v-pills-senha" role="tabpanel" aria-labelledby="v-pills-senha-tab">
            <p class="text-muted mb-3">Atualização de senhas</p>   
            <form class="row g-3" method="post" action="{{ url_for('perfil.update_id_perfil') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <div class="col">
                    <select class="form-select" name="id_perfil" aria-label="Default select example">
                        {% for perfil in perfis %}
                        <option value="{{ perfil.id }}">{{ perfil.nome }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col">
                    <input type="password" name="senha" class="form-control" placeholder="Nova senha">
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary">Alterar</button>
                </div>
            </form>

            <!-- Tabela de tipo de permissões -->
            <p class="text-muted mb-3 mt-4">Tipo de permissão por usuário</p>
            <div class="row">
                <div class="col-sm-8 border bg-white">
                    <table class="table mt-1">
                        <thead>
                            <tr>
                                <th scope="col">Usuário</th>
                                <th scope="col">Permissão</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for perfil in perfis %}
                            <tr>
                                <td>{{ perfil.nome }}</td>
                                <td>{{ perfil.descricao }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Dica de reset senhas -->
            <p class="text-muted mb-3 mt-4">Redefinição de todas a senhas</p>
            <div class="row">
                <div class="col-sm-8 border bg-white p-3">
                    <small class="text-muted d-block"># No servidor onde o container Docker está rodando, execute:</small>
                    <code>docker exec -it cmb python db-create.py --pwd</code>
                </div>
            </div> 

        </div><!-- /Senhas -->

    </div>
</div>